/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Ana
 */
public class FrmEntradasSalidas extends javax.swing.JFrame {

    /**
     * Creates new form FrmEntradasSalidas
     */
    public FrmEntradasSalidas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jopMensajeES = new javax.swing.JOptionPane();
        cmbNombreProductoES = new javax.swing.JComboBox<>();
        cmbTipoOperacionES = new javax.swing.JComboBox<>();
        lblTituloProductoES = new javax.swing.JLabel();
        lblTipoOperacionES = new javax.swing.JLabel();
        txtCantidadProductoES = new javax.swing.JTextField();
        lblCantidadES = new javax.swing.JLabel();
        btnAceptarES = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entradas y salidas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getContentPane().add(cmbNombreProductoES, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 290, -1));

        cmbTipoOperacionES.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Salida" }));
        getContentPane().add(cmbTipoOperacionES, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 290, -1));

        lblTituloProductoES.setText("Producto");
        getContentPane().add(lblTituloProductoES, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        lblTipoOperacionES.setText("Tipo de operación");
        getContentPane().add(lblTipoOperacionES, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));
        getContentPane().add(txtCantidadProductoES, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 290, -1));

        lblCantidadES.setText("Cantidad");
        getContentPane().add(lblCantidadES, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        btnAceptarES.setText("ACEPTAR");
        getContentPane().add(btnAceptarES, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEntradasSalidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEntradasSalidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEntradasSalidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEntradasSalidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEntradasSalidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptarES;
    public javax.swing.JComboBox<String> cmbNombreProductoES;
    public javax.swing.JComboBox<String> cmbTipoOperacionES;
    public javax.swing.JOptionPane jopMensajeES;
    private javax.swing.JLabel lblCantidadES;
    private javax.swing.JLabel lblTipoOperacionES;
    private javax.swing.JLabel lblTituloProductoES;
    public javax.swing.JTextField txtCantidadProductoES;
    // End of variables declaration//GEN-END:variables
}
