/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Ana
 */
public class FrmInventario extends javax.swing.JFrame {
    /**
     * Creates new form FrmInventario
     */
    public FrmInventario() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jopMensaje = new javax.swing.JOptionPane();
        pnlFondoBotones = new javax.swing.JPanel();
        btnPestaniaH = new javax.swing.JButton();
        btnPestaniaRP = new javax.swing.JButton();
        btnPestaniaES = new javax.swing.JButton();
        jtpPestanias = new javax.swing.JTabbedPane();
        pnlPestaniaRegistro = new javax.swing.JPanel();
        lblTituloProducto = new javax.swing.JLabel();
        txtNombreProductoRP = new javax.swing.JTextField();
        btnCrearProductoRP = new javax.swing.JButton();
        pnlPestaniaEntradasSalidas = new javax.swing.JPanel();
        cmbProductoES = new javax.swing.JComboBox<>();
        lblTituloProductoES = new javax.swing.JLabel();
        lblTituloTipoES = new javax.swing.JLabel();
        cmbTipoES = new javax.swing.JComboBox<>();
        lblTituloCantidadES = new javax.swing.JLabel();
        txtCantidadProductoES = new javax.swing.JTextField();
        btnAceptarES = new javax.swing.JButton();
        pnlPestaniaHistorial = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventarioProductosH = new javax.swing.JTable();
        lblTituloProductoH = new javax.swing.JLabel();
        btnMostrarInventarioH = new javax.swing.JButton();
        cmbProductosH = new javax.swing.JComboBox<>();
        pnlFondoPestanias = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondoBotones.setBackground(new java.awt.Color(0, 0, 102));
        pnlFondoBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPestaniaH.setBackground(new java.awt.Color(102, 153, 255));
        btnPestaniaH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPestaniaH.setForeground(new java.awt.Color(255, 255, 255));
        btnPestaniaH.setText("HISTORIAL");
        pnlFondoBotones.add(btnPestaniaH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 210, 80));

        btnPestaniaRP.setBackground(new java.awt.Color(102, 153, 255));
        btnPestaniaRP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPestaniaRP.setForeground(new java.awt.Color(255, 255, 255));
        btnPestaniaRP.setText("REGISTRO PRODUCTO");
        pnlFondoBotones.add(btnPestaniaRP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 210, 80));

        btnPestaniaES.setBackground(new java.awt.Color(102, 153, 255));
        btnPestaniaES.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPestaniaES.setForeground(new java.awt.Color(255, 255, 255));
        btnPestaniaES.setText("ENTRADAS Y SALIDAS");
        pnlFondoBotones.add(btnPestaniaES, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 210, 80));

        getContentPane().add(pnlFondoBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 500));

        pnlPestaniaRegistro.setBackground(new java.awt.Color(255, 255, 255));
        pnlPestaniaRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloProducto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloProducto.setText("Producto");
        pnlPestaniaRegistro.add(lblTituloProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        txtNombreProductoRP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnlPestaniaRegistro.add(txtNombreProductoRP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 370, -1));

        btnCrearProductoRP.setBackground(new java.awt.Color(0, 153, 153));
        btnCrearProductoRP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCrearProductoRP.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearProductoRP.setText("CREAR");
        pnlPestaniaRegistro.add(btnCrearProductoRP, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 130, 70));

        jtpPestanias.addTab("Registrar producto", pnlPestaniaRegistro);

        pnlPestaniaEntradasSalidas.setBackground(new java.awt.Color(255, 255, 255));
        pnlPestaniaEntradasSalidas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbProductoES.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnlPestaniaEntradasSalidas.add(cmbProductoES, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 380, -1));

        lblTituloProductoES.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloProductoES.setText("Producto");
        pnlPestaniaEntradasSalidas.add(lblTituloProductoES, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        lblTituloTipoES.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloTipoES.setText("Tipo de operación");
        pnlPestaniaEntradasSalidas.add(lblTituloTipoES, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        cmbTipoES.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTipoES.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Salida" }));
        pnlPestaniaEntradasSalidas.add(cmbTipoES, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 370, 30));

        lblTituloCantidadES.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloCantidadES.setText("Cantidad");
        pnlPestaniaEntradasSalidas.add(lblTituloCantidadES, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        txtCantidadProductoES.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnlPestaniaEntradasSalidas.add(txtCantidadProductoES, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 370, -1));

        btnAceptarES.setBackground(new java.awt.Color(0, 153, 153));
        btnAceptarES.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAceptarES.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptarES.setText("ACEPTAR");
        pnlPestaniaEntradasSalidas.add(btnAceptarES, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 130, 60));

        jtpPestanias.addTab("Entradas y Salidas", pnlPestaniaEntradasSalidas);

        pnlPestaniaHistorial.setBackground(new java.awt.Color(255, 255, 255));
        pnlPestaniaHistorial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblInventarioProductosH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Detalle", "Entrada", "Salida", "Existencias"
            }
        ));
        jScrollPane1.setViewportView(tblInventarioProductosH);

        pnlPestaniaHistorial.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 590, 320));

        lblTituloProductoH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloProductoH.setText("Producto");
        pnlPestaniaHistorial.add(lblTituloProductoH, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        btnMostrarInventarioH.setBackground(new java.awt.Color(0, 153, 153));
        btnMostrarInventarioH.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnMostrarInventarioH.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarInventarioH.setText("MOSTRAR INVENTARIO");
        pnlPestaniaHistorial.add(btnMostrarInventarioH, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 220, 70));

        cmbProductosH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnlPestaniaHistorial.add(cmbProductosH, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 350, -1));

        jtpPestanias.addTab("Historial", pnlPestaniaHistorial);

        getContentPane().add(jtpPestanias, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 650, 480));

        pnlFondoPestanias.setBackground(new java.awt.Color(102, 153, 255));
        pnlFondoPestanias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnlFondoPestanias, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 650, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptarES;
    public javax.swing.JButton btnCrearProductoRP;
    public javax.swing.JButton btnMostrarInventarioH;
    public javax.swing.JButton btnPestaniaES;
    public javax.swing.JButton btnPestaniaH;
    public javax.swing.JButton btnPestaniaRP;
    public javax.swing.JComboBox<String> cmbProductoES;
    public javax.swing.JComboBox<String> cmbProductosH;
    public javax.swing.JComboBox<String> cmbTipoES;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JOptionPane jopMensaje;
    public javax.swing.JTabbedPane jtpPestanias;
    private javax.swing.JLabel lblTituloCantidadES;
    private javax.swing.JLabel lblTituloProducto;
    private javax.swing.JLabel lblTituloProductoES;
    private javax.swing.JLabel lblTituloProductoH;
    private javax.swing.JLabel lblTituloTipoES;
    private javax.swing.JPanel pnlFondoBotones;
    private javax.swing.JPanel pnlFondoPestanias;
    public javax.swing.JPanel pnlPestaniaEntradasSalidas;
    public javax.swing.JPanel pnlPestaniaHistorial;
    public javax.swing.JPanel pnlPestaniaRegistro;
    public javax.swing.JTable tblInventarioProductosH;
    public javax.swing.JTextField txtCantidadProductoES;
    public javax.swing.JTextField txtNombreProductoRP;
    // End of variables declaration//GEN-END:variables
}