/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Ana
 */
public class FrmSnake extends javax.swing.JFrame {

    /**
     * Creates new form FrmSnake
     */
    public FrmSnake() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jopMensaje = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        btnAbajo = new javax.swing.JButton();
        btnArriba = new javax.swing.JButton();
        btnIzquierda = new javax.swing.JButton();
        btnDerecha = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbDificultad = new javax.swing.JComboBox<>();
        btnNuevoJuego = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblTamanioSnake = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblIntervaloSnake = new javax.swing.JLabel();
        pnlTablero = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Snake Game");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAbajo.setBackground(new java.awt.Color(253, 216, 253));
        btnAbajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/down.png"))); // NOI18N
        btnAbajo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAbajo.setEnabled(false);
        jPanel1.add(btnAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 60, 60));

        btnArriba.setBackground(new java.awt.Color(253, 216, 253));
        btnArriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/up.png"))); // NOI18N
        btnArriba.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnArriba.setEnabled(false);
        jPanel1.add(btnArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 60, 60));

        btnIzquierda.setBackground(new java.awt.Color(253, 216, 253));
        btnIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left.png"))); // NOI18N
        btnIzquierda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIzquierda.setEnabled(false);
        jPanel1.add(btnIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 60, 60));

        btnDerecha.setBackground(new java.awt.Color(253, 216, 253));
        btnDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/right.png"))); // NOI18N
        btnDerecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDerecha.setEnabled(false);
        btnDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerechaActionPerformed(evt);
            }
        });
        jPanel1.add(btnDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 60, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Dificultad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        cmbDificultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fácil", "Medio", "Difícil" }));
        jPanel1.add(cmbDificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 160, -1));

        btnNuevoJuego.setBackground(new java.awt.Color(255, 204, 204));
        btnNuevoJuego.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNuevoJuego.setText("Nuevo Juego");
        btnNuevoJuego.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnNuevoJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 150, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Tamaño serpiente");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        lblTamanioSnake.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTamanioSnake.setForeground(new java.awt.Color(51, 51, 51));
        lblTamanioSnake.setText("0");
        lblTamanioSnake.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblTamanioSnake, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 40, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Intervalo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        lblIntervaloSnake.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblIntervaloSnake.setForeground(new java.awt.Color(51, 51, 51));
        lblIntervaloSnake.setText("0");
        lblIntervaloSnake.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblIntervaloSnake, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 50, -1));

        pnlTablero.setPreferredSize(new java.awt.Dimension(300, 300));
        pnlTablero.setLayout(new java.awt.GridLayout(10, 10, 1, 1));
        jPanel1.add(pnlTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDerechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSnake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSnake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSnake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSnake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSnake().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAbajo;
    public javax.swing.JButton btnArriba;
    public javax.swing.JButton btnDerecha;
    public javax.swing.JButton btnIzquierda;
    public javax.swing.JButton btnNuevoJuego;
    public javax.swing.JComboBox<String> cmbDificultad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JOptionPane jopMensaje;
    public javax.swing.JLabel lblIntervaloSnake;
    public javax.swing.JLabel lblTamanioSnake;
    public javax.swing.JPanel pnlTablero;
    // End of variables declaration//GEN-END:variables
}
