/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Ana
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jopMensajeM = new javax.swing.JOptionPane();
        menuBar = new javax.swing.JMenuBar();
        menuCrear = new javax.swing.JMenu();
        mItemCrearCliente = new javax.swing.JMenuItem();
        mItemCrearCuenta = new javax.swing.JMenuItem();
        menuVer = new javax.swing.JMenu();
        mItemInformacionCliente = new javax.swing.JMenuItem();
        menuOperaciones = new javax.swing.JMenu();
        mItemDeposito = new javax.swing.JMenuItem();
        mItemTransferencia = new javax.swing.JMenuItem();
        mItemPagoServicios = new javax.swing.JMenuItem();
        menuHistorial = new javax.swing.JMenu();
        mItemHistorial = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú principal");

        menuCrear.setText("Crear");

        mItemCrearCliente.setText("Nuevo cliente");
        menuCrear.add(mItemCrearCliente);

        mItemCrearCuenta.setText("Nueva cuenta");
        menuCrear.add(mItemCrearCuenta);

        menuBar.add(menuCrear);

        menuVer.setText("Ver");

        mItemInformacionCliente.setText("Información clientes");
        menuVer.add(mItemInformacionCliente);

        menuBar.add(menuVer);

        menuOperaciones.setText("Operaciones");

        mItemDeposito.setText("Depósito monetario");
        menuOperaciones.add(mItemDeposito);

        mItemTransferencia.setText("Transferencia");
        menuOperaciones.add(mItemTransferencia);

        mItemPagoServicios.setText("Pago de servicios");
        menuOperaciones.add(mItemPagoServicios);

        menuBar.add(menuOperaciones);

        menuHistorial.setText("Historial");

        mItemHistorial.setText("Historial transacciones");
        menuHistorial.add(mItemHistorial);

        menuBar.add(menuHistorial);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JOptionPane jopMensajeM;
    public javax.swing.JMenuItem mItemCrearCliente;
    public javax.swing.JMenuItem mItemCrearCuenta;
    public javax.swing.JMenuItem mItemDeposito;
    public javax.swing.JMenuItem mItemHistorial;
    public javax.swing.JMenuItem mItemInformacionCliente;
    public javax.swing.JMenuItem mItemPagoServicios;
    public javax.swing.JMenuItem mItemTransferencia;
    private javax.swing.JMenuBar menuBar;
    public javax.swing.JMenu menuCrear;
    private javax.swing.JMenu menuHistorial;
    public javax.swing.JMenu menuOperaciones;
    public javax.swing.JMenu menuVer;
    // End of variables declaration//GEN-END:variables
}
